import React, { useState, useEffect, useCallback } from "react";
import Request from "./Request";
import { v4 as uuidv4 } from "uuid";

import { clickObserver } from "./Submissions";

export default function Requests() {
  const [requestNumber, setRequestNumber] = useState(1);
  const [countOfRandomRequests, setCountOfRandomRequests] = useState(0);

  useEffect(() => {
    if (requestNumber >= 1) {
      setRequestList((prevList) => [
        { requestNumber, key: uuidv4() },
        ...prevList
      ]);
    }
  }, [requestNumber]);

  const [requestList, setRequestList] = useState([]);

  const sendRequests = useCallback(
    function () {
      console.log("SUBMIT ME", requestList);
    },
    [requestList]
  );

  useEffect(() => {
    let submitObserver = clickObserver.subscribe({
      next: sendRequests
    });

    return () => submitObserver.unsubscribe();
  }, [sendRequests]);

  function addRequest(events, travelPlan) {
    setRequestNumber((prevReqNo) => prevReqNo + 1);
  }

  function removeRequest(requestNumber) {
    setRequestList(
      (prevList) =>
        (prevList.length > 1 &&
          prevList.filter((x) => x.requestNumber !== requestNumber)) ||
        prevList
    );
  }

  function resetRequestNumberCounter() {
    setRequestList((x) => {
      let resetRequestList = [...x];
      resetRequestList.forEach((y, i) => (y.requestNumber = x.length - i));

      return resetRequestList;
    });
  }

  function randomRequestGenerator(e) {
    e.persist();
    console.log("CALLED!!", countOfRandomRequests);
    setRequestList((requestList) => {
      let autoGeneratedRequestList = [];
      let localCount = countOfRandomRequests;
      while (localCount--) {
        // console.log("[TRACK]", localCount);
        autoGeneratedRequestList.push({
          requestNumber: requestNumber + 1 + localCount,
          key: uuidv4(),
          src: Math.round(Math.random() * 10000, 0),
          dest: Math.round(Math.random() * 10000, 0)
        });
      }

      console.log(e);

      return autoGeneratedRequestList.concat(requestList);
    });
  }

  return (
    <>
      <div className="requestControl">
        <button onClick={resetRequestNumberCounter}>
          Reset Request Counter
        </button>
        <button onClick={randomRequestGenerator}>
          Generate Random Requests
        </button>
        <input
          placeholder="How many Requests?"
          value={countOfRandomRequests}
          onChange={(e) => {
            console.log(e.target.value);
            setCountOfRandomRequests(
              e.target.value > 0 ? parseInt(e.target.value, 10) : 0
            );
          }}
        />
        <button
          onClick={() => setRequestList([{ requestNumber: 1, key: uuidv4() }])}
        >
          Reset Requests
        </button>
      </div>
      {requestList.map(
        (x) =>
          x.requestNumber && (
            <Request
              addRequest={addRequest}
              removeRequest={removeRequest}
              {...x}
            />
          )
      )}
    </>
  );
}
